In [47]:
import matplotlib.pyplot as plt
import numpy as np
from tensorflow import keras
import tensorflow as tf
from PIL import Image
import glob
import random
import pandas as pd

from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D, Input, AveragePooling2D
from tensorflow.keras.models import Sequential, load_model #
from tensorflow.keras import layers, preprocessing #
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.model_selection import train_test_split, GridSearchCV

import streamlit as st #
import os #
import tensorflow_hub as hub #


In [22]:
from tensorflow.keras.models import load_model

In [23]:
model_file_name = '../code_ben/my_model.h5'

# Load the model
loaded_model = load_model(model_file_name)

In [24]:
# Recreate the exact same model, including its weights and the optimizer
# new_model = tf.keras.models.load_model('/content/my_model.hdf5')

# Show the model architecture
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 average_pooling2d (Average  (None, 64, 64, 3)         0         
 Pooling2D)                                                      
                                                                 
 conv2d (Conv2D)             (None, 62, 62, 16)        448       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 16)        0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, 31, 31, 16)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        4640      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 14, 14, 32)        0

In [25]:
import pandas as pd

In [26]:
files=glob.glob("../hotdog-nothotdog/test/hotdog/*.jpg")
TestData = []
index = 0

for file in files:
    img = Image.open(file)
    img = img.resize((128, 128))
    imgarray = np.asarray(img)
    TestData.append((imgarray,1))

files=glob.glob("../hotdog-nothotdog/test/nothotdog/*.jpg")
index = 0
for file in files:
    img = Image.open(file)
    img = img.resize((128, 128))
    imgarray = np.asarray(img)
    TestData.append((imgarray,0))

print("Done.")

random.shuffle(TestData)

Done.


In [27]:
print("TestData ",len(TestData))

TestData  644


In [28]:
X_test = np.array([item[0] for item in TestData])
y_test = np.array([item[1] for item in TestData])

X_test = X_test.astype('float32')

X_test /= 255

In [113]:
predictions = (loaded_model.predict(X_test))


21/21 [==============================] - 0s 14ms/step


In [114]:
predictions 

array([[0.14414069],
       [0.7176999 ],
       [0.52809536],
       [0.6687778 ],
       [0.7229571 ],
       [0.50383586],
       [0.1260014 ],
       [0.55252326],
       [0.78092146],
       [0.1216865 ],
       [0.6420926 ],
       [0.71992123],
       [0.24602495],
       [0.8377291 ],
       [0.3399785 ],
       [0.08068383],
       [0.91098803],
       [0.6640692 ],
       [0.13088232],
       [0.7963127 ],
       [0.69035107],
       [0.12605056],
       [0.08055812],
       [0.7427396 ],
       [0.12076852],
       [0.07915609],
       [0.65372163],
       [0.51702017],
       [0.05796146],
       [0.10175261],
       [0.41179076],
       [0.13829494],
       [0.13825592],
       [0.55026287],
       [0.6927193 ],
       [0.29227793],
       [0.7518594 ],
       [0.7200467 ],
       [0.378426  ],
       [0.15259987],
       [0.36247012],
       [0.6237579 ],
       [0.8380791 ],
       [0.69853914],
       [0.49357063],
       [0.23491311],
       [0.05064708],
       [0.100

In [82]:
# scores = tf.nn.sigmoid(predictions)
# scores = (predictions)


In [115]:
scores = predictions

In [116]:
# scores = scores.numpy()
scores

array([[0.14414069],
       [0.7176999 ],
       [0.52809536],
       [0.6687778 ],
       [0.7229571 ],
       [0.50383586],
       [0.1260014 ],
       [0.55252326],
       [0.78092146],
       [0.1216865 ],
       [0.6420926 ],
       [0.71992123],
       [0.24602495],
       [0.8377291 ],
       [0.3399785 ],
       [0.08068383],
       [0.91098803],
       [0.6640692 ],
       [0.13088232],
       [0.7963127 ],
       [0.69035107],
       [0.12605056],
       [0.08055812],
       [0.7427396 ],
       [0.12076852],
       [0.07915609],
       [0.65372163],
       [0.51702017],
       [0.05796146],
       [0.10175261],
       [0.41179076],
       [0.13829494],
       [0.13825592],
       [0.55026287],
       [0.6927193 ],
       [0.29227793],
       [0.7518594 ],
       [0.7200467 ],
       [0.378426  ],
       [0.15259987],
       [0.36247012],
       [0.6237579 ],
       [0.8380791 ],
       [0.69853914],
       [0.49357063],
       [0.23491311],
       [0.05064708],
       [0.100

In [98]:
# scores = scores.numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

In [117]:
scores

array([[0.14414069],
       [0.7176999 ],
       [0.52809536],
       [0.6687778 ],
       [0.7229571 ],
       [0.50383586],
       [0.1260014 ],
       [0.55252326],
       [0.78092146],
       [0.1216865 ],
       [0.6420926 ],
       [0.71992123],
       [0.24602495],
       [0.8377291 ],
       [0.3399785 ],
       [0.08068383],
       [0.91098803],
       [0.6640692 ],
       [0.13088232],
       [0.7963127 ],
       [0.69035107],
       [0.12605056],
       [0.08055812],
       [0.7427396 ],
       [0.12076852],
       [0.07915609],
       [0.65372163],
       [0.51702017],
       [0.05796146],
       [0.10175261],
       [0.41179076],
       [0.13829494],
       [0.13825592],
       [0.55026287],
       [0.6927193 ],
       [0.29227793],
       [0.7518594 ],
       [0.7200467 ],
       [0.378426  ],
       [0.15259987],
       [0.36247012],
       [0.6237579 ],
       [0.8380791 ],
       [0.69853914],
       [0.49357063],
       [0.23491311],
       [0.05064708],
       [0.100

In [118]:
binary_predictions = (scores >= 0.5).astype(int)

In [119]:
binary_predictions

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [120]:
binary_predictions_flat = binary_predictions.ravel().astype(int)
binary_predictions_flat

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,

In [124]:
binary_predictions_flat[0]

0